FROM registry.access.redhat.com/ubi8/ubi

MAINTAINER Eric Löffler <eloeffler@aservo.com>

RUN yum makecache && \
    yum -y update && \
    yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm  && \
    yum -y install \
        ca-certificates \
        git \
        curl \
        jq \
        java-11-openjdk-headless \
        maven \
        && \
    yum clean all && \
    rm -rf /tmp/* /var/tmp/*

ADD ca_certs/ /usr/share/pki/ca-trust-source/anchors/
ADD src/ /opt/app/src/
ADD docker-entrypoint.sh /opt/app/
ADD docker-start.sh /opt/app/

RUN chmod -R 644 /usr/share/pki/ca-trust-source/anchors/ && \
    update-ca-trust

WORKDIR /opt/app

RUN ./docker-start.sh resolve-maven

ENTRYPOINT ["/opt/app/docker-entrypoint.sh"]

CMD ["/opt/app/docker-start.sh"]
